retrieval/train.py
This requires the update to RETRO-pytorch in PR#22.
=> Proper training loop for retrieval transformers

CODEOWNERS
This is necessary to enable reviewers to approve PRs in these directories.
=> Add `workloads` directory to CODEOWNERS

workloads/retro-next/build_knowledge_base/0000_build_chunk_index.sh, workloads/retro-next/build_knowledge_base/0001_precompute_emdeddings.sh, workloads/retro-next/build_knowledge_base/0002_save_index_spec.sh, workloads/retro-next/build_knowledge_base/0003_train_index.sh, workloads/retro-next/build_knowledge_base/0004_build_index.sh, workloads/retro-next/build_knowledge_base/0005_generate_neighbors.sh, workloads/retro-next/build_knowledge_base/Dockerfile, workloads/retro-next/build_knowledge_base/build.sh, workloads/retro-next/build_knowledge_base/index-spec.json, workloads/retro-next/build_knowledge_base/run.sh
The puprose of this PR is to provide a workload that can be built into a container. Then the container can be run to build the knowledge base.
The knowledge base indexing is modeled using a worklfow. The workflow contains serial steps numbered from 0000..00005. This PR isn't quite complete, specifically the paths are not set properly in all cases. Additionally the volume mounts needed to mount the host filesystem (to access the knowledge base jsonl file) is not completed.
=> Produce a knowledge base index

platform/packaging/build/libtorch/Dockerfile, platform/packaging/build/libtorch/build.sh
=> Build libtorch

kubernetes/README.md, kubernetes/crd/dataset.json, workloads/dataset-controller/Dockerfile, workloads/dataset-controller/README.md, workloads/dataset-controller/dataset-controller.py, workloads/dataset-controller/flake.lock, workloads/dataset-controller/flake.nix
This PR adds a k8s CRD for datasets, as well as a controller which reads CRs, retrieves datasets from HF Hub, and uploads them to an OCI bucket.
This needs more work, but it's worth taking a quick look. Things I should do:
* Cache-invalidation logic, two-phase commit: should use a timestamp and a success flag to ensure that we never have partial uploads or double uploads
* Support splits besides "train"?
* More metrics
=> Dataset controller, DataSet CRD v1

kubernetes/crd/dataset.json, workloads/dataset-controller/README.md, workloads/dataset-controller/flake.nix
Fix some stuff from #121 feedback.
=> Address review feedback

workloads/vllm/init.sh, workloads/vllm/run.sh
This initial prototype of running vllm with the web-chat repo in our organization.
=> Initial prototype of vllm

workloads/alexandria/LICENSE, workloads/alexandria/README.md, workloads/alexandria/data/datasets/Makefile, workloads/alexandria/data/datasets/MassiveOpenText/retriever_sentence_transformer/train.index.spec.json, workloads/alexandria/data/datasets/MassiveOpenText/retriever_sentence_transformer/val.index.spec.json, workloads/alexandria/data/datasets/MassiveOpenText/train_sentence_transformer_neighbours.spec.json, workloads/alexandria/data/datasets/MassiveOpenText/val_sentence_transformer_neighbours.spec.json, workloads/alexandria/data/datasets/README.md, workloads/alexandria/data/model/README.md, workloads/alexandria/data/model/retro.json, workloads/alexandria/src/data/build_faiss_index.py, workloads/alexandria/src/data/embed_chunks.py, workloads/alexandria/src/data/retrieve_neighbours.py, workloads/alexandria/src/data/tokenize_and_chunk.py, workloads/alexandria/src/data/train_faiss_index.py, workloads/alexandria/src/dataset_retro.py, workloads/alexandria/src/dataset_retro_demo.py, workloads/alexandria/src/evaluate_retro.py, workloads/alexandria/src/generate_retro.py, workloads/alexandria/src/modeling_retro.py, workloads/alexandria/src/retrieval.py, workloads/alexandria/src/test_modeling_retro.py, workloads/alexandria/src/train_retro.py
This is a good starting implementation. I have rewritten most of this and plan to re write all of it ;-). I did not wish to burden Tobias with our needs, so I made a copy of his repo.
T
=> Initial PR merging a retro implementation

kubernetes/crd/vectorindex.yaml, mouseion/mouseion/indexbuilder.py, mouseion/mouseion/train_and_build_index.py, workloads/vectorindex-controller/Dockerfile, workloads/vectorindex-controller/README.md, workloads/vectorindex-controller/flake.lock, workloads/vectorindex-controller/flake.nix, workloads/vectorindex-controller/vectorindex-controller.py
This is a possible way to incrementally build vector indices.
=> Start on a VectorIndex CRD and controller

.github/workflows/docker_build.yml
I probably won't get this right the first time, but that's life.
=> CI for building Dockerfiles

.github/workflows/docker_build.yml
See docker/build-push-action#105 or docker/build-push-action#254 for rationale and hints. I had thought that this would happen automatically, but we actually have to do it ourselves.
=> ci: Tag images appropriately

mouseion/mouseion/tasks.py
This code enables running a collection of tasks in paralell. Initially the code runs locally using
multiprocessing. Remote targets could be added in the future.
- Integration with our theme.
- Uses fork() as part of Multiprocess().
- Uses rich for screen management.
- Tasks can have dependencies.
(v-rich) sdake@wise-a40x2:~/repos/origin/mouseion/mouseion$ python tasks.py
Artificial Wisdom™ NLP Tools • RETRO Tokenizer
• Load jsonl • ━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • 0:00:00 • 0:00:03 •  10% •  •
• Tokenize   • ━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ • 0:00:00 • 0:00:06 •   5% •  •
=> Add a multiprocessing task handler

mouseion/mouseion/tasks.py
Adds a function to return task results
=> Return task results

mouseion/mouseion/tasks.py, mouseion/pyproject.toml
Added a specific start() operation instead of the janky approach used to start processes prior.
=> Rework tasks handling

platform/Dockerfiles/faiss/Dockerfile, platform/Dockerfiles/faiss/faiss-v1.8.0-introduce-epoch.patch, platform/Dockerfiles/faiss/faiss-v1.8.0-runpath-origin.patch, platform/Dockerfiles/faiss/faiss-v1.8.0-setuppy-include-binaries.patch
Update to v1.8.0 and build statically.
=> Update faiss to v1.8.0

mouseion/mouseion/maketokens.py
This code does the following using a source dataset:
- tokenize
- determine sequence to token
- determine token to sequence
- generate embedded tokens
=> Make token numpy arrays

mouseion/datacollection_specs/train-arxiv.json, mouseion/mouseion/dataset.py
A dataset class loads the various resources associated with a dataset.
=> Add the dataset lass

platform/Dockerfiles/faiss/Dockerfile
Updated newer docker requires changes to deprecated styling
Updated MKL library
=> Update faiss to 1.8.0+1

platform/Dockerfiles/faiss/Dockerfile, platform/Dockerfiles/faiss/build.sh
More cleanup within faiss
- Download mkl from Intel's apt repository
- Save tarball of mkl (/opt/facebook)
- Save tarball of cuda (/opt/nvidia)
- Version cleanups for consistency
=> faiss v1.8.0

platform/Dockerfiles/toolchain/Dockerfile, platform/Dockerfiles/toolchain/build.sh
- Includes Rust
- Includes Go
- Includes Python
- Includes C/C++
- Includes Intel MKL
- Includes NVIDIA Cuda
=> Unify the build toolchain
